### PR TITLE
Enhance Tab replace, Auto-parenthesis for single quote, better {} completion.

### PR DESCRIPTION
**Pull request by coder3101**
The following changes have been brought in this PR :
- Added auto-match and complete `'`. (single quote)
- In my last PR #13, I added auto indent on `{}` was added. However it was limited to `C++` and as soon as user types `{` the closing `}` was always placed in a new line. Now in this PR, the newline is placed only after user press newline key. This behavior is exactly same as QT Editor's behavior and is now available to all languages.
- Tab Replace when set to false, the indentation was still done using `Spaces`. Now, when it is set to false the editor places indents with `Tabs`. This behaviour is good because earlier in Python, lang Mix of spaces and Tabs would produce errors.

### CODE REVIEW

**Comment by coder3101** [comment]
@Megaxela Merge soon, I need to update my dependencies to new changes.

**Comment by Megaxela** [comment]
Nice work!
I wont complain with code style, cause I'll add clang-format soon. 
Thank you so much for you contribution.

**Comment by coder3101** [comment]
I used Google Code style. Yours was similar to Visual Studio. It would be nice if you could include your .clang-format file. So formatting will be okay

**Comment by Megaxela** [comment]
Yes, Google Code style is pretty interesting and well documented, but I tried to follow some Qt code style here. I don't know is it documented somewhere, but I'll make some research about it.
It's pretty possible, that I'll include common Google Code style if I wont find any Qt related info.

**Pull request merged**
